#!/bin/sh

path="$HOME/.simsalavim"

if [ -e $path/.git ]; then
    cd $path && git pull
else
    git clone https://github.com/danielemegna/simsalavim.git $path
fi

if [ ! -e $HOME/.vim/bundle/vundle ]; then
    git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
fi

ln -sf $path/vimrc ~/.vimrc

vim - +PluginInstall! +PluginClean! +qall
