#!/bin/sh

set -e

path="$HOME/.simsalavim"

if [ -e $path/.git ]; then
    cd $path && git pull --rebase --autostash
else
    git clone git@github.com:danielemegna/simsalavim.git $path
fi

if [ ! -e $HOME/.vim/autoload/plug.vim ]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

ln -sf $path/vimrc ~/.vimrc

vim +PlugUpgrade +PlugInstall +PlugUpdate +PlugClean +qall
